<?php

/**
 * @file
 * Code for the Stanford Story Page feature.
 */

include_once 'stanford_story_page.features.inc';

/**
 * Implements hook_preprocess_html().
 */
function stanford_story_page_preprocess_html(&$vars) {
  if (arg(0) == 'node' && ($node = node_load(arg(1)))) {
    $hide_title = field_get_items('node', $node, 'field_s_story_hide_title');
    if ($hide_title && $hide_title[0]['value']) {
      $vars['classes_array'][] = 'hide-title';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function stanford_story_page_preprocess_node(&$vars) {
  if ($vars['type'] == 'stanford_story_page' && $vars['page']) {
    drupal_add_css(drupal_get_path('module', 'stanford_story_page') . '/css/stanford_story_page.css');
  }
}
