<?php

/**
 * @file
 * Code for the Stanford Related Person feature.
 */

/**
 * Implements hook_views_default_views_alter().
 */
function stanford_related_person_views_default_views_alter(&$views) {
  stanford_related_person_alter_four_grid_block($views);
  stanford_related_person_alter_five_grid_block($views);
  stanford_related_person_alter_six_grid_block($views);
  //stanford_related_person_alter_page($views);
  stanford_related_person_alter_manage_person($views);
}

/**
 * Add exposed filter for related content to the page display.
 *
 * @param array $views
 *   Array of views.
 */
function stanford_related_person_alter_manage_person(&$views) {
  $view_name = 'stanford_person_manage';
  if (array_key_exists($view_name, $views)) {
    $view = $views[$view_name];
  }
  else {
    return FALSE;
  }

  $display_name = 'page';
  if ($view->set_display($display_name)) {
    $handler = $view->display_handler;
  }
  else {
    if (variable_get("stanford_related_debug_mode", FALSE)) {
      watchdog('stanford_related_person',
        "Display %display_name not available in view %view_name.",
        array('%display_name' => $display_name, '%view_name' => $view_name),
        WATCHDOG_DEBUG);
    }
    return FALSE;
  }

  // Add the exposed filter.
  return((stanford_related_content_add_exposed_filter($views, $view_name,
      $display_name, FALSE, "Related Content"))

    // Add the VBO.
    && (stanford_related_content_add_vbo($views, $view_name, $display_name))
  );
}

/**
 * Implements hook_views_pre_view().
 */
function stanford_related_person_views_pre_view(&$view, &$display_id, &$args) {

  // Insert the related content field after the location field
  if ($view->name == 'stanford_person_manage' && $view->current_display == "page") {
    stanford_related_content_insert_related_content($view, $display_id,
      'field_s_person_last_name');
  }
}

/**
 * Copy the block display in the stanford_news_view and add contextual filter.
 *
 * @param array $views
 *   Array of views.
 */
function stanford_related_person_alter_four_grid_block(&$views) {
  $view_name = 'stanford_person_grid';
  $display_name = 'block';
  if (array_key_exists($view_name, $views)) {
    $view = $views[$view_name];
  }
  else {
    if (variable_get("stanford_related_debug_mode", FALSE)) {
      watchdog('stanford_related_person', "View '%name' not available.",
        array('%name' => $view_name), WATCHDOG_DEBUG);
    }
    return FALSE;
  }

  /* Todo: Do we want to link to the people page?
  // Get the page URL.
  $page_handler = NULL;
  if (isset($view->display['page_1'])) {
    if ($view->set_display('page_1')) {
      $page_handler = $view->display_handler;
    }
  }

  // Is it overridden?
  elseif (isset($view->display['recent_person_page_2'])) {
    if ($view->set_display('recent_person_page_2')) {
      $page_handler = $view->display_handler;
    }
  }

  if ($page_handler == NULL) {
    watchdog('stanford_related_person', "Display not available in view %view_name.",
      array('%view_name' => $view_name), WATCHDOG_DEBUG);
    return FALSE;
  }
  $page_path = $page_handler->get_option('path');
  */

  // Copy the block display.
  $handler = stanford_related_content_copy_display($views,
    $view_name, $display_name, 'Filtered Block', 'filtered_block');
  if ($handler == FALSE) {
    return FALSE;
  }

  // Add contextual filter and more link.
  $handler = stanford_related_content_add_contextual_filter($handler,
    'Related People');
  /* TODO: If we link to a page
  $handler = stanford_related_content_add_footer_more_link($handler,
    $page_path);
  */

  // Check that the view still works after we altered it!
  if (stanford_related_content_validate_view($views[$view_name], 'stanford_related_person')) {
    if (variable_get("stanford_related_debug_mode", FALSE)) {
      watchdog('stanford_related_person',
        "Block %display_name added to view %view_name.",
        array('%display_name' => $display_name, '%view_name' => $view_name),
        WATCHDOG_DEBUG);
    }
    return TRUE;
  }
  return FALSE;
}

/**
 * Copy the block display in the stanford_grid_five_block.
 *
 * @param array $views
 *   Array of views.
 */
function stanford_related_person_alter_five_grid_block(&$views) {
  $dest_block = array(
    'title' => 'Related People',
    'display_title' => 'Filtered Block',
    'display_name' => 'filtered_grid_five_block',
  );

  return stanford_related_content_create_block($views,
    'stanford_person_grid_five', 'block', $dest_block);
}

/**
 * Copy the block display in the stanford_grid_six_block.
 *
 * @param object $views
 *   Array of views.
 */
function stanford_related_person_alter_six_grid_block(&$views) {
  $dest_block = array(
    'title' => 'Related People',
    'display_title' => 'Filtered Block',
    'display_name' => 'filtered_grid_six_block',
  );

  return stanford_related_content_create_block($views,
    'stanford_person_grid_six', 'block', $dest_block);
}
