<?php
/**
* Implement hook_install().
*
* Install, update and uninstall functions for the minimal installation profile.
*/
function stanford_sites_jumpstart_lab_install() {}

/**
 * Implements hook_uninstall().
 */
function stanford_sites_jumpstart_lab_uninstall() {}

/**
 * Implements hook_install_finished.
 */
function stanford_sites_jumpstart_lab_install_finished() {
  itasks_install_finished();
}
