<?php

/**
 * @file
 * Code for the Stanford Minimal Filter feature.
 */

/**
 * Implements hook_filter_info_alter().
 */
function stanford_minimal_filter_filter_info_alter(&$info) {
  // Add a prepare callback so that we can to some futzing.
  $info["pathologic"]["prepare callback"] = "stanford_paragraph_types_pathologic_prepare_callback";
}

/**
 * Implements hook_pathologic_alter().
 */
function stanford_minimal_filter_pathologic_prepare_callback($text, &$filter, $format, $langcode, $cache, $cache_id) {

  // Only alter on this one format...
  if ($format->format !== "minimal_html") {
    // Pathalogic requires text to be passed back.
    return $text;
  }

  if (!preg_match('/jsa-content/', $filter->settings['local_paths'])) {
    $filter->settings['local_paths'] = "/jsa-content/\nhttps://sites.stanford.edu/jsa-content/\n" . $filter->settings['local_paths'];
  }

  return $text;
}
