<?php
/**
 * @file
 * Functionality for the Stanford Date Formats module.
 */

/**
 * Implements hook_date_formats().
 */
function stanford_date_formats_date_formats() {
  $formats = array(
    array(
      'type' => 'stanford_time',
      'format' => 'g:ia',
    ),
    array(
      'type' => 'stanford_month_date_year',
      'format' => 'F j, Y',
    ),
    array(
      'type' => 'stanford_date_year_time',
      'format' => 'F j, Y - g:ia',
    ),
    array(
      'type' => 'stanford_date_year_time_space',
      'format' => 'F j, Y - g:i a',
    ),
    array(
      'type' => 'stanford_two_digit_day',
      'format' => 'd',
    ),
    array(
      'type' => 'stanford_short_month',
      'format' => 'M',
    ),
    array(
      'type' => 'stanford_short_month_day',
      'format' => 'M j',
    ),
    array(
      'type' => 'stanford_short_month_day_time',
      'format' => 'M j | g:ia ',
    ),
    array(
      'type' => 'stanford_short_month_day_time_space',
      'format' => 'M j | g:i a ',
    ),
    array(
      'type' => 'stanford_month_two_digit_date_year',
      'format' => 'F d, Y',
    ),
    array(
      'type' => 'stanford_long_day_date_year',
      'format' => 'l, F j, Y',
    ),
    array(
      'type' => 'stanford_long_day_date_year_time',
      'format' => 'l, F j, Y - g:ia',
    ),
    array(
      'type' => 'stanford_long_day_date_year_time_space',
      'format' => 'l, F j, Y - g:i a',
    ),
  );

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function stanford_date_formats_date_format_types() {
  $types = array(
    'stanford_time' => t('Time'),
    'stanford_month_date_year' => t('Month Date, Year'),
    'stanford_date_year_time' => t('Date, Year - Time'),
    'stanford_date_year_time_space' => t('Date, Year - Time with space'),
    'stanford_two_digit_day' => t('Two Digit Day'),
    'stanford_short_month' => t('Short Month'),
    'stanford_short_month_day' => t('Short Month Day'),
    'stanford_short_month_day_time' => t('Short Month Day | Time'),
    'stanford_short_month_day_time_space' => t('Short Month Day | Time with space'),
    'stanford_month_two_digit_date_year' => t('Month Two-Digit Day, Year'),
    'stanford_long_day_date_year' => t('Long Day of Week, Date, Year'),
    'stanford_long_day_date_year_time' => t('Long Day of Week, Date, Year - Time'),
    'stanford_long_day_date_year_time_space' => t('Long Day of Week, Date, Year - Time with space'),
  );

  return $types;
}
