<?php
/**
 * @file
 * Install functions for Stanford Date Formats module
 */

/**
 * Implements hook_install().
 */
function stanford_date_formats_install() {
  variable_set('date_format_stanford_time', 'g:ia');
  variable_set('date_format_stanford_month_date_year', 'F j, Y');
  variable_set('date_format_stanford_date_year_time', 'F j, Y - g:ia');
  variable_set('date_format_stanford_date_year_time_space', 'F j, Y - g:i a');
  variable_set('date_format_stanford_two_digit_day', 'd');
  variable_set('date_format_stanford_short_month', 'M');
  variable_set('date_format_stanford_short_month_day', 'M j');
  variable_set('date_format_stanford_short_month_day_time', 'M j | g:ia');
  variable_set('date_format_stanford_short_month_day_time_space', 'M j | g:i a');
  variable_set('date_format_stanford_month_two_digit_date_year', 'F d, Y');
  variable_set('date_format_stanford_long_day_date_year', 'l, F j, Y');
  variable_set('date_format_stanford_long_day_date_year_time', 'l, F j, Y - g:ia');
  variable_set('date_format_stanford_long_day_date_year_time_space', 'l, F j, Y - g:i a');
}
