<?php
/**
 * @file
 * Code for the Stanford Carousel feature.
 */

include_once 'stanford_carousel.features.inc';

/**
 * Implements template_preprocess_html().
 */
function stanford_carousel_preprocess_html($variables) {
  drupal_add_js(drupal_get_path('module', 'stanford_carousel') . '/js/stanford_carousel_aria.js', array('group' => JS_THEME, 'weight' => '100'));
}

/**
 * Implements hook_help().
 */
function stanford_carousel_help($path, $arg) {
  switch ($path) {
    case 'admin/help#stanford_carousel':
      $output = "<h2>To Use</h2>";
      $output .= "<h3>Create One or More Slide Nodes</h3>";
      $output .= "<ol>";
      $output .= "	<li>Go to node/add/stanford-slide</li>";
      $output .= "	<li>Upload your image</li>";
      $output .= "	<li>Choose your caption options</li>";
      $output .= "</ol>";
      $output .= "<h3>Place the Carousel</h3>";
      $output .= "<p>There are 6 options, each is a Views block display:</p>";
      $output .= "<ul>";
      $output .= "	<li>No Caption - Span 9: A carousel without captions that spans 9 columns</li>";
      $output .= "	<li>No Caption - Span 12: A carousel without captions that spans 12 columns</li>";
      $output .= "	<li>Caption - Span 9: A carousel that spans 9 columns, with a flexible-height caption background</li>";
      $output .= "	<li>Caption - Span 12: A carousel that spans 12 columns, with a flexible-height caption background</li>";
      $output .= "	<li>Caption Block - Span 9: A carousel that spans 9 columns, with a full-height caption background</li>";
      $output .= "	<li>Caption Block - Span 12: A carousel that spans 12 columns, with a full-height caption background</li>";
      $output .= "</ul>";
      $output .= "<p>You can place the desired block using the core block system, or using Context or Panels.</p>";
      $output .= "<h2>Requirements</h2>";
      $output .= "<p>Drupal 7</p>";
      $output .= "<p>The Stanford Carousel requires Twitter Bootstrap version 2. Use it with any Open Framework-based theme (tested with 7.x-2.06 and above) and it should &quot;just work&quot;.</p>";
      $output .= "<p>&nbsp;</p>";
      return $output;
  }
}

/**
 * Hook Theme
 * @param  [type] $existing [description]
 * @param  [type] $type     [description]
 * @param  [type] $theme    [description]
 * @param  [type] $path     [description]
 * @return [type]           [description]
 */
function stanford_carousel_theme($existing, $type, $theme, $path) {
  return array (
    'views_view_unformatted__stanford_carousel' => array (
      'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'base hook' => 'views_view_unformatted',
      'template' => 'views-view-unformatted--stanford-carousel',
      'path' => drupal_get_path('module', 'stanford_carousel') . "/templates",
    ),
  );
}
