<?php
/**
 * @file
 * stanford_paragraph_types_textarea_simple.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function stanford_paragraph_types_textarea_simple_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_p_ws_body'.
  $field_bases['field_p_ws_body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_p_ws_body',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_p_ws_image'.
  $field_bases['field_p_ws_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_p_ws_image',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  return $field_bases;
}
