<?php
/**
 * @file
 * stanford_icon_grid.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function stanford_icon_grid_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_s_icon_ext_columns'.
  $field_bases['field_s_icon_ext_columns'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns',
    'indexes' => array(
      'revision_id' => array(
        0 => 'revision_id',
      ),
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'field_collection',
    'settings' => array(
      'hide_blank_items' => 1,
      'hide_initial_item' => FALSE,
      'path' => '',
    ),
    'translatable' => 0,
    'type' => 'field_collection',
  );

  // Exported field_base: 'field_s_icon_ext_columns_bg_colo'.
  $field_bases['field_s_icon_ext_columns_bg_colo'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_bg_colo',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '#8c1515,#ffffff' => 'Red',
        '#000000,#ffffff' => 'Black',
        '#ffffff,#000000' => 'White',
        '#4d4f53,#ffffff' => 'Cool Gray',
        '#928b81,#ffffff' => 'Dark Taupe',
        '#d5d0c0,#ffffff' => 'Light Taupe',
        '#006374,#ffffff' => 'Deep Blue',
        '#53284f,#ffffff' => 'Deep Purple',
        '#009b76,#ffffff' => 'Bright Green',
        '#0f6c91,#ffffff' => 'Bright Blue',
        '#eaab00,#ffffff' => 'Bright Yellow',
        '#e98300,#ffffff' => 'Bright Orange',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_s_icon_ext_columns_caption'.
  $field_bases['field_s_icon_ext_columns_caption'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_caption',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_s_icon_ext_columns_fa_icon'.
  $field_bases['field_s_icon_ext_columns_fa_icon'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_fa_icon',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'stanford_field_formatters',
    'settings' => array(
      'subset' => NULL,
    ),
    'translatable' => 0,
    'type' => 'fontawesome_icon',
  );

  // Exported field_base: 'field_s_icon_ext_columns_links'.
  $field_bases['field_s_icon_ext_columns_links'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_links',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'link',
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'rel' => '',
        'target' => 'default',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'title' => 'optional',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
    ),
    'translatable' => 0,
    'type' => 'link_field',
  );

  // Exported field_base: 'field_s_icon_ext_columns_style'.
  $field_bases['field_s_icon_ext_columns_style'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_style',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'icon' => 'FontAwesome Icon',
        'image' => 'Image File',
        'text' => 'Text/Number',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_s_icon_ext_columns_text'.
  $field_bases['field_s_icon_ext_columns_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_text',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 5,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_s_icon_ext_columns_title'.
  $field_bases['field_s_icon_ext_columns_title'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_title',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_s_icon_ext_columns_up_icon'.
  $field_bases['field_s_icon_ext_columns_up_icon'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_columns_up_icon',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  // Exported field_base: 'field_s_icon_ext_num_row'.
  $field_bases['field_s_icon_ext_num_row'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_s_icon_ext_num_row',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 4,
        6 => 6,
        12 => 12,
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_integer',
  );

  return $field_bases;
}
