<?php

/**
 * Implements hook_boot().
 *
 * Require the Composer Autoload File.
 */
function composer_autoloader_boot() {

  // Define the default path to the  composer autoloader.
  $default = DRUPAL_ROOT . '/../vendor/autoload.php';

  // Allow the path to be modified by $conf.
  $autoloader = variable_get('composer_autoloader', $default);

  // Determine if the file exists.
  if (!file_exists($autoloader)) {

    // The error message text.
    $text = 'Autoloader not found: @file';

    // Variables for the text.
    $variables = array('@file' => $autoloader);

    // Trigger an error.
    trigger_error(t($text, $variables), E_USER_ERROR);

    // End the function.
    return;

  }

  // Require the Autoloader.
  require_once $autoloader;

}
