<?php

/**
 * @file
 * Composer Autoloader.
 */

/**
 * Returns Composer's class loader.
 *
 * @return \Composer\Autoload\ClassLoader|null
 *   Composer's class loader.
 */
function composer_autoloader() {
  static $autoloader;

  if ($autoloader === NULL) {
    $composer_autoloader = variable_get('composer_autoloader', DRUPAL_ROOT . '/../vendor/autoload.php');

    if (file_exists($composer_autoloader)) {
      $autoloader = require $composer_autoloader;
    }
    else {
      trigger_error(sprintf('Composer autoloader was not found at "%s".', $composer_autoloader), E_USER_ERROR);
    }
  }

  return $autoloader;
}

/**
 * Implements hook_boot().
 *
 * @internal
 */
function composer_autoloader_boot() {
  composer_autoloader();
}
