languages:
   Ruby: false
   JavaScript: true
   Python: false
   PHP: true
exclude_paths:
- "*.features*.inc"
- "*.field_group.inc"
- "*.strongarm*.inc"
- "*.context*.inc"
- "*.ds.inc"
- "*.views_default.inc"
