<?php
/**
 * @file
 * Code for the Stanford Person feature.
 */

include_once 'stanford_person.features.inc';

/**
 * function hook_form_alter()
 */
function stanford_person_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == "stanford_person_node_form"){
    $form ['title'] ['#description'] = '<p>' . t('If left empty, this optional text field is populated from the "First name" and "Last name" fields.') . '</p>';
  }
}
