<?php
/**
 * @file
 * Code for the Stanford Jumpstart Layouts feature.
 */

include_once 'stanford_jumpstart_layouts.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function stanford_jumpstart_layouts_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'stanford_jumpstart_layouts-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Menu - Primary - 1 Depth',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'stanford_jumpstart_layouts-2' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Menu - Secondary - 2 Depths',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 2,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
