<?php
/**
 * @file
 * @author Caryl Westerberg <cjwest@stanford.edu>
 * Installation tasks.
 */

/**
 * Implements hook_install().
 */
function stanford_jse_layouts_install() {
}

/**
 * Implements hook_enable().
 */
function stanford_jse_layouts_enable() {
}

/**
 * Implements hook_disable().
 */
function stanford_jse_layouts_disable() {
}

/**
 * Implements hook_uninstall().
 */
function stanford_jse_layouts_uninstall() {
}
