<?php
/**
 * Provides the markup for the issue collector.
 */

/**
 * Implements hook_help().
 */
function capx_issue_collector_help($path, $arg) {
  switch ($path) {
    case 'capx#issue-collector':
      return '<p>' . t('No help available.') . '</p>';
  }
}

/**
 * Only attach JS on node edit and admin pages.
 * @param  [type] $vars [description]
 * @return [type]       [description]
 */
function capx_issue_collector_preprocess_page(&$vars) {

  $a0 = arg(0);
  $a1 = arg(1);
  $a2 = arg(2);
  $admin = path_is_admin(current_path());
  $js = drupal_get_path("module", "capx_issue_collector") . "/capx_issue_collector.js";

  if ($admin) {
    drupal_add_js($js);
  }
  elseif ($a0 == "node" && $a2 == "edit") {
    drupal_add_js($js);
  }

}
