<?php

/**
 * @file
 * Stanford Parapgraph Types Install/Uninstall.
 */

/**
 * Clear old values of texture data.
 */
function stanford_paragraph_types_update_7010() {
  if (db_table_exists('field_data_field_p_card_pattern')) {
    db_truncate('field_data_field_p_card_pattern')->execute();
  }
  if (db_table_exists('field_revision_field_p_card_pattern')) {
    db_truncate('field_revision_field_p_card_pattern')->execute();
  }
}
