<?php
/**
 * @file
 * Code for the Stanford Image feature.
 */

include_once 'stanford_image.features.inc';

/**
 * Implements hook_form_alter().
 */
function stanford_image_form_alter(&$form, &$form_state, $form_id) {

  // Check for field collection field.
  if (!isset($form['field_s_image_info'])) {
    return;
  }

  // Set the height for all wysiwyg fields in a field collection.
  foreach ($form['field_s_image_info'][LANGUAGE_NONE] as $index => &$values) {
    if (!is_int($index)) {
      continue;
    }

    foreach ($values['field_s_image_caption'][LANGUAGE_NONE] as $field_index => &$field_values) {
      if (!is_int($field_index)) {
        continue;
      }
      $height = intval($field_values["#rows"] * 13);
      $field_values['#attributes']['style'][] = "height: " . $height . "px;";
    }
  }

}
