<?php
/**
 * @file
 * Code for the Stanford Video feature.
 */

include_once 'stanford_video.features.inc';

/**
 * Implements hook_field_formatter_info().
 */
function stanford_video_field_formatter_info() {
  $formatters = array(
    'stanford_video' => array(
      'label' => t('Stanford Web Video'),
      'field types' => array('file', 'link_field'),
      'settings' => array(
        'jwplayer_preset' => '',
      ),
    ),
  );
  return $formatters;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function stanford_video_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $element = array();

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  // Formatter types.
  switch ($display['type']) {
    case 'stanford_video':
      $presets = jw_player_preset_load();

      // If there are presets prompt the user to select one or create another.
      // If no, prompt to create a preset.
      if (!empty($presets)) {
        foreach (jw_player_preset_load() as $preset => $item) {
          $options[$preset] = $item['preset_name'];
        }

        $element['jwplayer_preset'] = array(
          '#title' => t('Select preset'),
          '#type' => 'select',
          '#default_value' => ($settings['jwplayer_preset']) ?  $settings['jwplayer_preset'] : FALSE,
          '#options' => $options,
        );
        $element['links'] = array(
          '#theme' => 'links',
          '#links' => array(
            array(
              'title' => t('Create new preset'),
              'href' => 'admin/config/media/jw_player/add',
            ),
            array(
              'title' => t('Manage presets'),
              'href' => 'admin/config/media/jw_player',
            ),
          ),
        );
      }
      else {
        $element['no_preset_message'] = array(
          '#markup' => '<div class="messages warning">' . t('No presets are available. You must to <a href="@create">create a preset</a> to proceed.', array('@create' => url('admin/config/media/jw_player/add'))) . '</div>',
        );
      }
      break;

    default:
      break;
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function stanford_video_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();
  $presets = jw_player_preset_load();

  if (isset($presets[$settings['jwplayer_preset']])) {
    $summary[] = t('Preset: @name', array('@name' => $presets[$settings['jwplayer_preset']]['preset_name']));
    $summary[] = t('Description: @description', array('@description' => $presets[$settings['jwplayer_preset']]['description']));

    $settings = $presets[$settings['jwplayer_preset']]['settings'];
    foreach ($settings as $key => $val) {
      // Filter out complex settings in the form of arrays (such as plugins).
      // @todo Tackle the display of enabled plugins separately.
      if (!is_array($val)) {
        $summary[] = t('@key: @val', array('@key' => $key, '@val' => !empty($val) ? $val : t('default')));
      }
    }
  }
  else {
    $summary[] = t('No preset selected');
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function stanford_video_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  if ($display['type'] == 'stanford_video') {
    // Process files for the theme function.
    $files = array();
    foreach ($items as $delta => $item) {
      switch ($field['type']) {
        case 'file':
          $files[$delta] = (object) $item;
          break;
        case 'link_field':
          // Manual override for WebM, because Drupal doesn't detect it.
          if (substr($item['url'], -5) == '.webm') {
            $mime = 'video/webm';
          }
          else {
            $mime = file_get_mimetype($item['url']);
          }
          // If the mime type is application/octet-stream, default to MP4.
          // This happens for instance for links without extensions.
          if ($mime == 'application/octet-stream') {
            $mime = 'video/mp4';
          }
          $files[$delta] = new stdClass();
          $files[$delta]->uri = $item['url'];
          $files[$delta]->filemime = $mime;
          break;
      }
    }
    // set some variables based on other fields in the entity
    $captions = '';
    $filename = '';
    $streamer = '';
    $poster = '';
    if (!empty($entity->field_stanford_video_caption)) {
      $captions = $entity->field_stanford_video_caption[$langcode][0]['uri'];
    }
    if (!empty($entity->field_stanford_video_filename)) {
      $filename = $entity->field_stanford_video_filename[LANGUAGE_NONE][0]['safe_value'];
    }
    if (!empty($entity->field_stanford_video_server) && (!empty($entity->field_stanford_video_account))) {
      $streamer = $entity->field_stanford_video_server[LANGUAGE_NONE][0]['safe_value'] . $entity->field_stanford_video_account[LANGUAGE_NONE][0]['safe_value'];
    }
    if (!empty($entity->field_stanford_video_poster) && (!empty($entity->field_stanford_video_poster))) {
      $poster = $entity->field_stanford_video_poster[LANGUAGE_NONE][0]['uri'];
    }
    foreach ($files as $delta => $file) {
      $element[$delta] = array(
        '#theme' => 'jw_player',
        '#file_object' => $file,
        '#preset' => $display['settings']['jwplayer_preset'],
        '#captions' => file_create_url($captions),
        '#filename' => $filename,
        '#streamer' => $streamer,
        '#poster' => file_create_url($poster),
      );
    }
  }
  return $element;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_video_form_stanford_video_node_form_alter(&$form, &$form_state, $form_id) {
  //make our validation function run first
  if (is_array($form['#validate'])) {
    array_unshift($form['#validate'], 'stanford_video_node_validate');
  }
  else {
    $form['#validate'][] = 'stanford_video_node_validate';
  }
  $form['field_stanford_video_external']['#access'] = user_access('embed external web video');
}

/**
 * Implements hook_help().
 */
function stanford_video_help($path, $arg) {
  switch ($path) {
    case 'admin/help#stanford_video' :
      $output = '<h2>' . t('To Use') . '</h2>';
      $output .= '<p>' . t('Create a new video node at !addvideo.', array('!addvideo' => l('node/add/stanford-video', 'node/add/stanford-video'))) . '</p>';
      $output .= '<p>' . t('You can upload videos directly (.flv, .mp3, .mp4, .m4v, .webm) and attach captions (.srt, .dfxp, .xml).') . '</p>';
      $output .= '<p>' . t('You also can stream videos from an RTMP streamer; the URL for the Stanford Video streaming server is provided by default.') . '</p>';
      $output .= '<p>' . t('If you organize your videos into directories and subdirectories on the Stanford Video streaming server, include the directory name(s) in the "File Name" field when creating a video node.') . '</p>';
      $output .= '<p>' . t('For more information on streaming video hosting through Stanford Video, visit !streaming.', array('!streaming' => l('http://stanfordvideo.stanford.edu/streaming', 'http://stanfordvideo.stanford.edu/streaming'))) . '</p>';
      $output .= '<p>' . t('For more information on creating caption files for videos, visit !captioning.', array('!captioning' => l('http://captioning.stanford.edu', 'http://captioning.stanford.edu'))) . '</p>';
      $output .= '<p>' . t('You also can embed videos from third-party providers (YouTube, Vimeo, etc.) by pasting the embed code into the "External Video Embed" field.') . '</p>';
      $output .= '<p>' . t('This field relies on the "Full HTML" text format. You should only grant access to that text format to trusted users and roles.') . '</p>';
      
      return $output;
  }
}
/**
 * Validation function for stanford_video_form_stanford_video_node_form_alter().
 */
function stanford_video_node_validate($form, &$form_state) {
  $concat_link = '';
  // only do this if we're not rebuilding the form, otherwise Drupal complains
  if(isset($form_state['rebuild']) && (!$form_state['rebuild'])) {
    // only do *this* if the user has set something in the server and filename fields; otherwise, leave the link field blank
    if(!empty($form_state['values']['field_stanford_video_server'][LANGUAGE_NONE][0]['value']) && !empty($form_state['values']['field_stanford_video_account'][LANGUAGE_NONE][0]['value'])) {
      $concat_link = $form_state['values']['field_stanford_video_server'][LANGUAGE_NONE][0]['value'] . $form_state['values']['field_stanford_video_account'][LANGUAGE_NONE][0]['value'] . '/' . $form_state['values']['field_stanford_video_filename'][LANGUAGE_NONE][0]['value'];
      $form_state['values']['field_stanford_video_link'][LANGUAGE_NONE][0]['url'] = $concat_link;
    }

    // check if they've entered something in multiple competing fields
    $message = t('You can only post one video type (Streaming Video, Uploaded Video, or External Embedded Video).');
    $linkfield = $form_state['values']['field_stanford_video_link'][LANGUAGE_NONE][0]['url'];
    $filefield = $form_state['values']['field_stanford_video_file'][LANGUAGE_NONE][0]['fid'];
    $embedfield = $form_state['values']['field_stanford_video_external'][LANGUAGE_NONE][0]['value'];
    if(!empty($linkfield)) {
      if(!empty($filefield)) {
        $field = 'field_stanford_video_filename';
        form_set_error($field, $message);
      }
      if(!empty($embedfield)) {
        $field = 'field_stanford_video_external';
        form_set_error($field, $message);        
      }
    }
    elseif(!empty($filefield)) {
      if(!empty($embedfield)) {
        $field = 'field_stanford_video_external';
        form_set_error($field, $message);        
      }      
    }
  }
}

/**
 * Implements hook_permission().
 */
function stanford_video_permission() {
  return array (
    'embed external web video' => array(
      'title' => t('Embed external web video'),
      'description' => t('Allow user to paste embed code (iframe, etc.) from external video providers.'),
      'restrict access' => TRUE,
    ),
  );
}
/**
 * Implements hook_preprocess_HOOK().
 * 
 * Process variables for jw_player.tpl.php.
 *
 * @param $variables
 *
 */
function stanford_video_preprocess_jw_player(&$variables) {
  if (isset($variables['file_object'])) {
    if (empty($variables['file_url'])) {
      $variables['file_url'] = file_create_url($variables['file_object']->uri);
    }
    //if a URL couldn't be created, set it to the remote URI
    // @todo this can probably be fixed with https://drupal.org/project/filter_protocols; see https://drupal.org/node/685592
    if (empty($variables['file_url'])) {
//      $variables['file_url'] = $variables['file_object']->uri;
      //make it empty?
      $variables['file_url'] = '';
    }
  }
  if(!empty($variables['streamer'])) {
    $variables['streaming'] = TRUE;
  }
  else {
    $variables['streaming'] = FALSE;
  }
  //streaming variables
  $variables['config']['file'] = $variables['filename'];
  $variables['config']['streamer'] = $variables['streamer'];
  $variables['config']['poster'] = $variables['poster'];
  $variables['config']['plugins'] = array();
  $variables['config']['plugins']['captions-2'] = array();
  $variables['config']['plugins']['captions-2']['state'] = TRUE;
  $variables['config']['plugins']['captions-2']['file'] = $variables['captions'];
}

/**
 * Implements hook_theme().
 */
function stanford_video_theme($existing = 'jw_player') {
  return array(
    'jw_player' => array(
      'variables' => array(
        'file_object' => NULL,
        'streamer' => '',
        'filename' => '',
        'preset' => '',
        'image' => '',
        'options' => array(),
        'entity' => NULL,
        'entity_type' => '',
        'captions' => '',
        'poster' => '',
      ),
      'template' => 'theme/stanford_jw_player',
    ),
  );
}
