<?php

/**
 * @file
 * views_select_sort.module
 */

/**
 * Implements hook_views_data_alter().
 */
function views_select_sort_views_data_alter(&$data) {
  $fields = field_read_fields(array('type' => 'list_text'));
  foreach (array_keys($fields) as $field_name) {
    if (isset($data["field_data_$field_name"])) {
      $value = $data["field_data_$field_name"]["{$field_name}_value"];
      $value['title'] = t('!title Customized', array('!title' => $value['title']));
      $value['title short'] = t('!short Customized', array('!short' => $value['title short']));
      unset($value['filter'], $value['argument']);
      $value['sort']['handler'] = 'ViewsSelectSort';
      $data["field_data_$field_name"]["{$field_name}_value_customize"] = $value;
    }
  }
}

/**
 * Implements hook_theme().
 */
function views_select_sort_theme($existing, $type, $theme, $path) {
  return array(
    'views_select_sort_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Create the draggable table for the StanfordDateViewsSortCustom.
 *
 * @param array $vars
 *   Theme array values.
 *
 * @return string
 *   Rendered output
 */
function theme_views_select_sort_form($vars) {
  $form = $vars['form'];
  $item_order = $vars['form']['item_order'];

  foreach (element_children($item_order) as $value) {
    $form['item_order'][$value]['weight']['#attributes']['class'] = array('slides-order-weight');
    $rows[] = array(
      'data' => array(
        array('class' => array('slide-cross')),
        drupal_render($form['item_order'][$value]['label']),
        drupal_render($form['item_order'][$value]['weight']),
      ),
      'class' => array('draggable'),
    );
  }

  $header = array('', t('Key'), t('Weight'));
  $output = drupal_render($form['form_description']);
  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => 'views-select-sort-table'),
  ));
  $output .= drupal_render_children($form);

  drupal_add_tabledrag('views-select-sort-table', 'order', 'sibling', 'slides-order-weight');

  return $output;
}