<?php
/**
 * @file
 * This file overrides the default course views to change their link from
 * explorecourses to the node itself.
 */

/**
 * hook_field_views_data_alter
 * hook_field_views_data_views_data_alter
 * hook_views_data_alter
 *
 * hook_views_pre_execute
 * hook_views_query_alter
 *
 * hook_views_pre_view
 */

/**
 * Alter all the things!
 * @param  [type] $view [description]
 * @return [type]       [description]
 */
function stanford_courses_link_to_page_views_pre_build(&$view) {

    $allowed = sucl_is_allowed_display($view);
    if (!$allowed) {
      return;
    }

    // Initial attempt was to disable the rewrite and set the 'link to node' setting.
    // Somewhere this breaks and does not render any link

    //  $view->field['title']->options['alter']['make_link'] = 0;
    //  $view->field['title']->options['alter']['absolute'] = 0;
    //  $view->field['title']->options['alter']['external'] = 1;
    //  $view->field['title']->options['alter']['path'] = '';
    //  $view->field['title']->options['link_to_node'] = 1;

}

/**
 * @param $view
 */
function stanford_courses_link_to_page_views_pre_render(&$view) {

  $allowed = sucl_is_allowed_display($view);
  if (!$allowed) {
    return;
  }

  if (!isset($view->field['field_s_course_ec_link']) && isset($view->result[0]->field_field_s_course_ec_link)) {
    return;
  }

  foreach ($view->result as $k => &$result) {
    $path = drupal_get_path_alias('node/' . $result->nid);
    $result->field_field_s_course_ec_link[0]['rendered'] = url($path, array('absolute' => TRUE));
    $result->field_field_s_course_ec_link[0]['raw']['url'] = url($path, array('absolute' => TRUE));
    $result->field_field_s_course_ec_link[0]['raw']['display_url'] = url($path, array('absolute' => TRUE));
  }

}


/**
 * @param $view
 * @return bool
 */
function sucl_is_allowed_display($view) {
    $name = $view->name;
    $display = $view->current_display;
    $allowed_views = array(
        'courses',
        'courses_reference',
    );
    $allowed_displays = array(
        'current_courses_page',
    );

    // if (in_array($name, $allowed_views) && in_array($display, $allowed_displays)) {
    //     return true;
    // }

    if (in_array($name, $allowed_views)) {
      return true;
    }

    return false;
}
