<?php

/**
 * @file
 * Stanford Paragraph Types Defaults.
 */

/**
 * Implements hook_features_api().
 */
function stanford_paragraphs_defaults_features_api() {
  return array(
    'paragraphs_defaults' => array(
      'default_hook' => 'paragraphs_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'feature_source' => TRUE,
      'file' => drupal_get_path('module', 'stanford_paragraphs_defaults') . '/stanford_paragraphs_defaults.features.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function stanford_paragraphs_defaults_permission() {
  return array(
    'administer stanford paragraph types defaults' => array(
      'title' => t('Administer Paragraph Types Defaults'),
      'description' => t('Create, modify, & delete default paragraph items.'),
    ),
    'create stanford paragraph types defaults' => array(
      'title' => t('Create Paragraph Types Defaults'),
      'description' => t('Create new default layouts.'),
    ),
  );
}

/**
 * Check if user has permission.
 *
 * @param string $operation
 *   Operation desired.
 *
 * @return bool
 *   If the user has access to the operation.
 */
function stanford_paragraph_defaults_administer($operation) {
  switch ($operation) {
    case 'administer':
      if (user_access('administer stanford paragraph types defaults')) {
        return TRUE;
      }
      break;

    case 'create':
      if (user_access('administer stanford paragraph types defaults') || user_access('create stanford paragraph types defaults')) {
        return TRUE;
      }
      break;
  }
  return FALSE;
}

/**
 * Implements hook_entity_delete().
 */
function stanford_paragraphs_defaults_entity_delete($entity, $type) {
  if ($type == 'paragraphs_item') {
    $item_id = $entity->item_id;

    $query = db_select('stanford_paragraphs_defaults', 's')
      ->fields('s', array('uid', 'item_ids'))
      ->condition('item_ids', "%:$item_id;%", 'LIKE')
      ->execute()
      ->fetchAllKeyed();

    foreach ($query as $uid => $item_ids) {

      $default_items = unserialize($item_ids);
      unset($default_items[$item_id]);

      // If only one of the paragraph items was deleted.
      if ($default_items) {
        db_update('stanford_paragraphs_defaults')
          ->fields(array('item_ids' => serialize($default_items)))
          ->condition('uid', $uid)
          ->execute();
      }
      else {
        // If all paragraph items were deleted.
        db_delete('stanford_paragraphs_defaults')
          ->condition('uid', $uid)->execute();
      }
    }
  }
}

/**
 * Implements hook_menu().
 */
function stanford_paragraphs_defaults_menu() {
  $items = array();
  $items['admin/structure/paragraphs/stanford-defaults'] = array(
    'title' => 'Defaults',
    'page callback' => 'stanford_paragraphs_defaults_overview',
    'file' => 'stanford_paragraphs_defaults.forms.inc',
    'access callback' => 'stanford_paragraph_defaults_administer',
    'access arguments' => array('create'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
  );
  $items['admin/structure/paragraphs/stanford-defaults/overview'] = array(
    'title' => 'Defaults',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/paragraphs/stanford-defaults/add/%/%/%'] = array(
    'title' => 'Add Default',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_paragraphs_defaults_add', 5, 6, 7),
    'file' => 'stanford_paragraphs_defaults.forms.inc',
    'access callback' => 'stanford_paragraph_defaults_administer',
    'access arguments' => array('create'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/paragraphs/stanford-defaults/edit/%stanford_paragraphs_defaults'] = array(
    'title' => 'Edit Default',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_paragraphs_defaults_edit', 5),
    'file' => 'stanford_paragraphs_defaults.forms.inc',
    'access callback' => 'stanford_paragraph_defaults_administer',
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/paragraphs/stanford-defaults/delete/%stanford_paragraphs_defaults'] = array(
    'title' => 'Delete Default',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_paragraphs_defaults_delete', 5),
    'file' => 'stanford_paragraphs_defaults.forms.inc',
    'access callback' => 'stanford_paragraph_defaults_administer',
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Delete the desired default configuration.
 *
 * @param string $uid
 *   The unique uid of the item to delete.
 */
function stanford_paragraphs_defaults_delete_default($uid) {
  $default = stanford_paragraphs_defaults_load($uid);
  if ($default) {
    // Queue up the paragraph items to prevent various errors from occuring
    // during the feature revert process.
    foreach (array_keys($default['item_ids']) as $item_id) {
      $queue = DrupalQueue::get('stanford_paragraphs_defaults_cron_cleanup');
      $queue->createItem(array('paragraphs_item' => $item_id));
    }

    db_delete('stanford_paragraphs_defaults')
      ->condition('uid', $uid)
      ->execute();
  }
}

/**
 * Load a single default configuration by uid.
 *
 * @param string $uid
 *   UID to load.
 *
 * @return array|bool
 *   Keyed array of the requested default or false if none exists.
 */
function stanford_paragraphs_defaults_load($uid) {
  if ($default = stanford_paragraphs_defaults_load_multiple(array($uid))) {
    return $default[$uid];
  }
  return FALSE;
}

/**
 * Loads multiple default configurations by requested UID.
 *
 * @param array|null $uids
 *   UIDs to load.
 * @param string $entity_type
 *   Entity type to load defaults.
 * @param string $bundle
 *   Entity bundle to load defaults.
 * @param string $field_name
 *   Entity field to load defaults.
 *
 * @return array
 *   An associative array with all available defaults.
 */
function stanford_paragraphs_defaults_load_multiple($uids = NULL, $entity_type = NULL, $bundle = NULL, $field_name = NULL) {
  $query = db_select('stanford_paragraphs_defaults', 's')
    ->fields('s');

  // Add any conditions passed in.
  if ($uids) {
    $query->condition('uid', $uids, 'IN');
  }
  if ($entity_type) {
    $query->condition('entity_type', $entity_type);
  }
  if ($bundle) {
    $query->condition('bundle', $bundle);
  }
  if ($field_name) {
    $query->condition('field_name', $field_name);
  }
  $results = $query->execute();

  $defaults = array();
  while ($default_item = $results->fetchAssoc()) {
    $item_ids = unserialize($default_item['item_ids']);
    $default_item['item_ids'] = $item_ids;

    // Sort paragraph items based on weight before loading.
    asort($item_ids);
    $paragraphs = paragraphs_item_load_multiple(array_keys($item_ids), array(), TRUE);
    $default_item['paragraphs'] = $paragraphs;

    $defaults[$default_item['uid']] = $default_item;
  }
  return $defaults;
}

/**
 * Implements hook_field_attach_form().
 */
function stanford_paragraphs_defaults_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  $uid = _stanford_paragraphs_defaults_get_form_uid($entity_type, $form['#bundle'], $form_state);

  // Load a desired default configuration.
  if ($uid) {
    _stanford_paragraphs_defaults_attach_default($form, $form_state, $uid);
  }

  $paragraphs_fields = field_read_fields(array(
    'type' => 'paragraphs',
    'entity_type' => $entity_type,
    'bundle' => $form['#bundle'],
  ));

  foreach (array_keys($paragraphs_fields) as $field_name) {
    $defaults = stanford_paragraphs_defaults_load_multiple(NULL, $entity_type, $form['#bundle'], $field_name);
    $state = field_form_get_state(array(), $field_name, LANGUAGE_NONE, $form_state);

    // Skip this field if its already populated, if the default config was
    // already loaded, or if no defaults are configured.
    if ($state['items_count']) {
      $form[$field_name][LANGUAGE_NONE]['add_more']['new_default'] = array(
        '#type' => 'submit',
        '#value' => t('Create new default from current content'),
        '#name' => 'stanford_paragraphs_defaults_create_default_existing',
        '#submit' => array('stanford_paragraphs_defaults_create_default_existing'),
        '#access' => stanford_paragraph_defaults_administer('create'),
        '#entity_type' => $form_state['field'][$field_name][LANGUAGE_NONE]['instance']['entity_type'],
        '#bundle' => $form_state['field'][$field_name][LANGUAGE_NONE]['instance']['bundle'],
      );
      continue;
    }
    elseif (!$defaults ||
      !isset($form[$field_name]) ||
      (strpos($uid, $field_name) !== FALSE)
    ) {
      continue;
    }

    // Attach the buttons.
    $form[$field_name][LANGUAGE_NONE]['defaults'] = array(
      '#type' => 'fieldset',
      '#title' => t('Start with a default layout'),
      '#weight' => -99,
      '#bundle' => NULL,
    );
    foreach ($defaults as $uid => $default) {
      $form[$field_name][LANGUAGE_NONE]['defaults'][$uid] = array(
        '#type' => 'submit',
        '#value' => $default['label'],
        '#name' => $uid,
        '#submit' => array('stanford_paragraphs_defaults_build_default'),
        '#limit_validation_errors' => array(),
        '#bundle' => NULL,
      );
    }
  }
}

/**
 * Create a new default layout from existing content.
 */
function stanford_paragraphs_defaults_create_default_existing($form, &$form_state) {
  module_load_include('inc', 'stanford_paragraphs_defaults', 'stanford_paragraphs_defaults.forms');
  $field_name = reset($form_state['triggering_element']['#parents']);
  $entity_type = $form_state['triggering_element']['#entity_type'];
  $bundle = $form_state['triggering_element']['#bundle'];
  $paragraphs = $form_state['values'][$field_name];

  // Clone paragraph items.
  foreach ($paragraphs[LANGUAGE_NONE] as $key => &$paragraph) {
    if (!isset($paragraph['entity'])) {
      unset($paragraphs[LANGUAGE_NONE][$key]);
      continue;
    }
    $paragraph['entity'] = stanford_pragraphs_defaults_replicate_entity('paragraphs_item', $paragraph['entity']);
  }

  // Create fake form_state to pass to
  // _stanford_paragraphs_defaults_machine_name().
  $state = array(
    'entity_info' => array(
      'entity_type' => $entity_type,
      'bundle' => $bundle,
      'field_name' => $field_name,
    ),
  );

  $machine_name = preg_replace("/[^A-Za-z0-9_]/", '_', $form_state['values']['title']);
  $machine_name = strtolower($machine_name);
  $increment = '';

  // Get unique machine name & label from the entity label.
  while (_stanford_paragraphs_defaults_machine_name(trim("{$machine_name}_$increment", '_'), $form, $state)) {
    if (!$increment) {
      $increment = 0;
    }
    $increment++;
  }

  // Save new paragraph default setting.
  $label = trim($form_state['values']['title'] . ' ' . $increment);
  $machine_name = trim("{$machine_name}_$increment", '_');
  stanford_paragraphs_defaults_save_defaults($entity_type, $bundle, $field_name, $label, $machine_name, $paragraphs);

  $url = "admin/structure/paragraphs/stanford-defaults/edit/$entity_type-$bundle-$field_name-$machine_name";
  drupal_set_message(t('New default layout %label saved. Edit new layout at !url', array(
    '%label' => $label,
    '!url' => l($url, $url),
  )));

  $form_state['rebuild'] = TRUE;
}

/**
 * Obtain the defaults uid from either $_GET or the form_state value.
 *
 * @param string $entity_type
 *   Entity type of the form.
 * @param string $entity_bundle
 *   Entity bundle of the form.
 * @param array $form_state
 *   Form values.
 *
 * @return string
 *   The uid to load.
 */
function _stanford_paragraphs_defaults_get_form_uid($entity_type, $entity_bundle, array $form_state) {
  $uid = '';
  $get = drupal_get_query_parameters($_GET);
  if (isset($get['layout'])) {
    $layout = check_plain($get['layout']);
    $uid = "$entity_type-$entity_bundle-$layout";
  }

  if (isset($form_state['load_default'])) {
    $uid = $form_state['load_default'];
  }
  return $uid;
}

/**
 * Attach the default paragraph configuration.
 *
 * @param array $form
 *   Drupal_get_form form array.
 * @param array $form_state
 *   Drupal_get_form form_state array.
 * @param string $uid
 *   Uid of the default configuration to load.
 */
function _stanford_paragraphs_defaults_attach_default(array &$form, array &$form_state, $uid) {
  $default = _stanford_paragraphs_defaults_attach_default_load($form, $form_state, $uid);
  // Already loaded default or no default exits.
  if (!$default) {
    return;
  }

  $field_name = $default['field_name'];
  $entity_type = $default['entity_type'];

  $entity = isset($form['#node']) ? $form['#node'] : $form['#entity'];
  $info = entity_get_info($entity_type);
  // Make sure the bundle key is set.
  // @see entity_extract_ids().
  if (!empty($info['entity keys']['bundle']) && !isset($entity->{$info['entity keys']['bundle']})) {
    $entity->{$info['entity keys']['bundle']} = $default['bundle'];
  }

  // Get field and instance from form state if its there.
  // This is mostly a tiny performance improvement.
  if (isset($form_state['field'][$field_name])) {
    $field = $form_state['field'][$field_name][LANGUAGE_NONE]['field'];
    $instance = $form_state['field'][$field_name][LANGUAGE_NONE]['instance'];
  }
  else {
    $field = field_info_field($field_name);
    $instance = field_info_instance($entity_type, $field_name, $default['bundle']);
  }

  // Reset the paragraph field.
  unset($form[$field_name]);
  unset($form_state['field'][$field_name]);

  // Order any existing paragraphs in a form we can use to set the
  // default value.
  $items = array();
  foreach ($default['paragraphs'] as $paragraphs_item) {
    $cloned_item = stanford_pragraphs_defaults_replicate_entity('paragraphs_item', $paragraphs_item);
    $items[]['entity'] = $cloned_item;
  }

  // Add new field to the form.
  $paragraphs_field = field_default_form($entity_type, $entity, $field, $instance, LANGUAGE_NONE, $items, $form, $form_state);
  $form += (array) $paragraphs_field;

  // Change form state with new item count.
  $field_form_state = &$form_state['field'][$field_name][LANGUAGE_NONE];
  $field_form_state['items_count'] = $field_form_state['real_items_count'] = count($items);
  $field_form_state['field'] = $field;
}

/**
 * Get the default configuration if valid.
 *
 * @param array $form
 *   Drupal_get_form form array.
 * @param array $form_state
 *   Drupal_get_form form_state array.
 * @param string $uid
 *   Uid of the default configuration to load.
 *
 * @return array|bool
 *   Default configuration or false if already loaded or should not be loaded.
 */
function _stanford_paragraphs_defaults_attach_default_load(&$form, &$form_state, $uid) {
  // Prevent loading the default over and over and over...
  $loaded = &drupal_static(__FUNCTION__ . ':' . $uid);
  if ($loaded) {
    return FALSE;
  }
  $loaded = TRUE;

  // Make sure the default setting exits.
  $default = stanford_paragraphs_defaults_load($uid);
  if (!$default) {
    return FALSE;
  }

  $field_name = $default['field_name'];
  $field_state = field_form_get_state(array(), $field_name, LANGUAGE_NONE, $form_state);

  // Make sure the field exists on the form & defaults can be loaded.
  if (!isset($form[$field_name]) || $field_state['items_count']) {
    return FALSE;
  }

  return $default;
}

/**
 * Default button submit handler.
 *
 * Rebuild the form with the form_state changed to indicate which default to
 * load.
 */
function stanford_paragraphs_defaults_build_default(&$form, &$form_state) {
  $form_state['load_default'] = $form_state['triggering_element']['#name'];
  $form_state['rebuild'] = TRUE;
}

/**
 * Implements hook_cron().
 */
function stanford_paragraphs_defaults_cron() {
  // Periodically prune the defaults configuration if the entity
  // type/bundle/field is no longer available.
  $defaults = stanford_paragraphs_defaults_load_multiple();
  foreach ($defaults as $default) {
    $field = field_info_instance($default['entity_type'], $default['field_name'], $default['bundle']);
    if (!$field) {
      entity_delete('paragraphs_item', array_keys($default['item_ids']));
    }
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function stanford_paragraphs_defaults_cron_queue_info() {
  $queues['stanford_paragraphs_defaults_cron_cleanup'] = array(
    'worker callback' => 'stanford_paragraphs_defaults_cron_cleanup',
    'time' => 60,
  );
  return $queues;
}

/**
 * Cron queue worker callback.
 *
 * @param array $item
 *   Paragraph item to clean with the key as the entity type, value as the ID.
 */
function stanford_paragraphs_defaults_cron_cleanup(array $item) {
  $type = key($item);
  $entity_id = $item[$type];
  entity_delete($type, $entity_id);
}

/**
 * Replicate the entity passed in argument.
 *
 * This function does not save the replicated entity. Taken from replicate
 * contrib module.
 *
 * @param string $entity_type
 *   The entity type.
 * @param object $entity
 *   The entity to replicate.
 *
 * @return object
 *   A new replicated entity.
 *
 * @see https://www.drupal.org/project/replicate
 */
function stanford_pragraphs_defaults_replicate_entity($entity_type, $entity) {
  $clone = clone $entity;

  if ($clone) {
    // Let other modules manage the cleaning of the entity.
    foreach (module_implements('replicate_entity_' . $entity_type) as $module) {
      $function = $module . '_replicate_entity_' . $entity_type;
      $function($clone);
    }
    $entity_info = entity_get_info($entity_type);

    // Set the entity as new entity.
    $clone->is_new = TRUE;

    // Clear the primary keys.
    $id_key = $entity_info['entity keys']['id'];
    $revision_key = $entity_info['entity keys']['revision'];
    $clone->{$id_key} = NULL;
    $clone->{$revision_key} = NULL;

    // Let other modules do special actions on each field.
    stanford_pragraphs_defaults_replicate_fields($clone, $entity_type);

    // Let other modules do special actions on the global entity.
    drupal_alter('replicate_entity', $clone, $entity_type, $entity);
  }

  return $clone;
}

/**
 * Replicate the fields of an entity.
 *
 * Taken from replicate contrib module.
 *
 * @param object $entity
 *   The entity for which to clone the fields.
 * @param string $entity_type
 *   The entity type.
 *
 * @see https://www.drupal.org/project/replicate
 */
function stanford_pragraphs_defaults_replicate_fields(&$entity, $entity_type) {
  foreach (field_info_fields() as $field_name => $field) {
    if (isset($entity->$field_name)) {
      // Here call hook functions. Doesn't use module_invoke because we
      // want to pass the clone by reference.
      foreach (module_implements('replicate_field_' . $field['type']) as $module) {
        $function = $module . '_replicate_field_' . $field['type'];
        $function($entity, $entity_type, $field_name);
      }
    }
  }
}
