<?php
/**
 * @file
 * Code for the Stanford News Views feature.
 */

include_once 'stanford_news_views.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function stanford_news_views_views_pre_render(&$view) {

  // Only pull in the css if it the news grid view is in use.
  $valid = array(
    'stanford_news_grid',
  );

  // Add the css for the news_grid view.
  if (in_array($view->name, $valid)) {
    drupal_add_css(drupal_get_path("module", "stanford_news_views") . "/css/stanford_news_views_grid.css");
  }
}
