<?php

/**
 * @file
 * Stanford Alt Check Module.
 */

define('STANFORD_ALT_CHECK_PER_PAGE', 10);

/**
 * Implements hook_ctools_plugin_api().
 */
function stanford_alt_check_ctools_plugin_api($owner, $api) {
  if ($owner == "context" && $api == "context") {
    return array("version" => 3);
  }
}

/**
 * Implements hook_permission().
 */
function stanford_alt_check_permission() {
  return array(
    'access alt check page' => array(
      'title' => t('Access Alt Check Overview'),
      'description' => t('Allow access to the alt check overview page, but not access to edit alt attributes.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_alt_check_menu() {
  $items = array();
  $items['admin/content/images'] = array(
    'title' => "Images",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_form'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access alt check page'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Manage Content Menu Items.
  $items['admin/images'] = array(
    'title' => "Manage Images",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_form'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access alt check page'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-manage-content-by-type',
  );

  return $items;
}

/**
 * Implements hook_cron_queue_info().
 */
function stanford_alt_check_cron_queue_info() {
  $queues['stanford_alt_check'] = array(
    'worker callback' => '_stanford_alt_check_rescan_entity_queue',
    'time' => 60,
  );
  return $queues;
}

/**
 * Implements hook_entity_insert().
 */
function stanford_alt_check_entity_insert($entity, $type) {
  _stanford_alt_check_clear_entity($entity, $type);

  list($entity_id, , $bundle) = entity_extract_ids($type, $entity);
  list($host_entity, $host_type, $host_bundle, , $host_title, $host_uri, $host_status) = _stanford_alt_check_get_host($entity, $type);
  $images = _stanford_alt_check_entity_images($entity, $type, $bundle);

  // Cant find host entity. This normally happens with field collections on
  // old revisions.
  if (!$host_entity) {
    return;
  }

  $entity_info = entity_get_info($host_type);
  foreach ($images as $field_type => $fields) {
    foreach ($fields as $field_name => $deltas) {
      foreach ($deltas as $delta => $field_images) {
        foreach ($field_images as $position => $image) {
          $record = array(
            'uri' => $image['uri'],
            'alt_text' => $image['alt'],
            'entity_id' => $entity_id,
            'entity_type' => $type,
            'entity_field' => $field_name,
            'entity_field_wysiwyg' => $field_type == 'wysiwyg',
            'host_title' => $host_title,
            'host_type' => $entity_info['label'],
            'host_bundle' => $entity_info['bundles'][$host_bundle]['label'],
            'host_changed' => $host_entity->changed ? $host_entity->changed : time(),
            'host_published' => $host_status,
            'image_meta' => serialize(array(
              'delta' => $delta,
              'position' => $position,
              'host_uri' => $host_uri,
              'raw_url' => $image['raw_url'],
            )),
          );
          drupal_write_record('stanford_alt_check', $record);
        }
      }
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function stanford_alt_check_entity_update($entity, $type) {
  stanford_alt_check_entity_insert($entity, $type);
}

/**
 * Implements hook_entity_delete().
 */
function stanford_alt_check_entity_delete($entity, $type) {
  _stanford_alt_check_clear_entity($entity, $type);
}

/**
 * Implements hook_theme().
 */
function stanford_alt_check_theme($existing, $type, $theme, $path) {
  return array(
    'stanford_alt_check_form' => array(
      'render element' => 'form',
      'file' => 'stanford_alt_check.theme.inc',
    ),
  );
}

/**
 * Recursive function that will continue down to the greates host entity.
 *
 * @param object $entity
 *   The actual entity to get host data from.
 * @param string $type
 *   The type of the entity we are inspecting.
 *
 * @return array|bool
 *   Array of host entity data or FALSE if it fails to obtain host.
 */
function _stanford_alt_check_get_host($entity, $type) {
  $host_type = NULL;
  switch ($type) {
    case 'field_collection_item':
      // Field Collection entities: Change $host_type & $host_entity to host
      // entity.
      $host_entity = $entity->hostEntity();
      $host_type = $entity->hostEntityType();
      if (!($item = _stanford_alt_check_get_host($host_entity, $host_type))) {
        return FALSE;
      }
      list($host_entity, $host_type) = $item;
      break;

    case 'paragraphs_item':
      /** @param ParagraphsItemEntity $entity */
      if ($host_entity = $entity->hostEntity()) {
        $host_type = $entity->hostEntityType();
        break;
      }

      // Paragraph Item entities: Change $host_type& $host_entityto host entity.
      // We use field query because the
      // ParagraphsItemEntity::hostEntityType() &
      // ParagraphsItemEntity::hostEntity() do not always work.
      $query = new EntityFieldQuery();
      $query->fieldCondition($entity->field_name, 'value', $entity->item_id);
      if ($results = $query->execute()) {
        $types = array_keys($results);
        $host_type = reset($types);
        $entity_loaded = entity_load($host_type, array_keys($results[$host_type]));
        $host_entity = reset($entity_loaded);
        if (!($item = _stanford_alt_check_get_host($host_entity, $host_type))) {
          return FALSE;
        }
        list($host_entity, $host_type) = $item;
      }
      break;

    default:
      $host_type = $type;
      $host_entity = $entity;
      break;
  }

  if ($host_entity && $host_type) {
    $meta = _stanford_alt_check_get_host_meta($host_type, $host_entity);
    return array(
      $host_entity,
      $host_type,
      $meta['bundle'],
      $meta['id'],
      $meta['title'],
      $meta['uri'],
      $meta['status'],
    );
  }
  return FALSE;
}

/**
 * Parse the entity to obtain the data we need.
 *
 * @param string $type
 *   The type of the entity.
 * @param object $entity
 *   Entity to get data from.
 *
 * @return array
 *   Keyed array of the needed data
 */
function _stanford_alt_check_get_host_meta($type, $entity) {
  list($entity_id, , $bundle) = entity_extract_ids($type, $entity);

  $title = '';
  if (isset($entity->title)) {
    $title = $entity->title;
  }
  // Beans use label property instead.
  if ($type == 'bean') {
    $title = $entity->label;
  }

  // All entities that don't have status property.
  $published = 1;
  // Mainly nodes which have status.
  if (isset($entity->status)) {
    $published = $entity->status;
  }

  $uri = entity_uri($type, $entity);
  return array(
    'id' => $entity_id,
    'bundle' => $bundle,
    'title' => $title,
    'uri' => $uri['path'],
    'status' => $published,
  );
}

/**
 * Clears all the entries in the table for the given entity.
 *
 * @param object $entity
 *   Entity to clear.
 * @param string $type
 *   Type of the entity.
 */
function _stanford_alt_check_clear_entity($entity, $type) {
  list($entity_id, ,) = entity_extract_ids($type, $entity);
  db_delete('stanford_alt_check')
    ->condition('entity_id', $entity_id)
    ->condition('entity_type', $type)
    ->execute();
}

/**
 * Parse the entity to obtain all images in any field.
 *
 * @param object $entity
 *   The entity to parse.
 * @param string $type
 *   The type of the entity.
 * @param string $bundle
 *   The bundle of the entity.
 *
 * @return array
 *   All images keyed by if they are in a wysiwyg field or upload.
 */
function _stanford_alt_check_entity_images($entity, $type, $bundle) {
  $images = array();
  $text_fields = array('text', 'text_long', 'text_with_summary');
  foreach (field_info_instances($type, $bundle) as $field_name => $instance) {
    $field = field_info_field($field_name);
    if (in_array($field['type'], $text_fields) && $instance['settings']['text_processing']) {
      // WYSIWYG Field.
      if ($items = field_get_items($type, $entity, $field_name)) {
        $images['wysiwyg'][$field_name] = _stanford_alt_check_wysiwyg_images($items);
      }
      continue;
    }

    if ($field['type'] == 'image') {
      // Image Field.
      if ($items = field_get_items($type, $entity, $field_name)) {
        $images['upload'][$field_name] = _stanford_alt_check_upload_images($items);
      }
    }
  }
  return $images;
}

/**
 * Process field data items to get the uri and the alt text.
 *
 * @param array $items
 *   Field items from field_get_items().
 *
 * @return array
 *   All images from the field keyed by the delta.
 */
function _stanford_alt_check_upload_images(array $items) {
  $images = array();
  foreach ($items as $delta => $item) {
    $file = file_load($item['fid']);
    if (!isset($item['alt'])) {
      $item['alt'] = '';
    }
    $images[$delta][0] = array(
      'uri' => $file->uri,
      'alt' => $item['alt'],
      'raw_url' => $file->uri,
    );
  }
  return $images;
}

/**
 * Parse the html in wysiwyg fields to get the <img> elements.
 *
 * @param array $items
 *   Field items from field_get_items().
 *
 * @return array
 *   All images from the field keyed by the delta and the position in the html.
 */
function _stanford_alt_check_wysiwyg_images(array $items) {
  $images = array();
  foreach ($items as $delta => $item) {

    $dom = new DOMDocument();
    libxml_use_internal_errors(TRUE);
    $dom->loadHTML($item['value']);
    $raw_images = $dom->getElementsByTagName('img');

    $dom = new DOMDocument();
    $dom->loadHTML(check_markup($item['value'], $item['format']));

    foreach ($dom->getElementsByTagName('img') as $position => $image) {
      $raw_source = $raw_images->item($position)->getAttribute('src');
      $images[$delta][$position] = _stanford_alt_check_wysiwyg_image($image);
      $images[$delta][$position]['raw_url'] = $raw_source;
    }
  }
  return $images;
}

/**
 * Process the <img> tag to get the src and alt attributes.
 *
 * @param \DOMElement $image
 *   The image element to parse.
 *
 * @return array
 *   Keyed array of the uri and alt text.
 */
function _stanford_alt_check_wysiwyg_image(DOMElement $image) {
  $src = $image->getAttribute('src');
  $src_parts = parse_url($src);

  // Sets the uri for external images.
  $uri = $src;

  global $base_url;
  if (!isset($src_parts['host']) || strpos($base_url, $src_parts['host']) !== FALSE) {
    if (strpos($src_parts['path'], '/styles/') !== FALSE) {
      // Image derivative.
      $exploded = explode('/', $src_parts['path']);
      $style_pos = array_search('styles', $exploded) + 3;
      $src = '//' . implode('/', array_slice($exploded, $style_pos));
    }
    else {
      // Original Image.
      $src = str_replace(variable_get('file_public_path'), '', $src_parts['path']);
      $src = str_replace(variable_get('file_private_path'), '', $src);
      $src = '//' . trim($src, '/');
    }
  }

  // Check if the image exists in some image field.
  $fid = db_select('file_managed', 'f')
    ->fields('f', array('fid'))
    ->condition('uri', "%$src", 'like')
    ->execute()
    ->fetchField();

  if ($fid) {
    $file = file_load($fid);
    $uri = $file->uri;
  }
  return array(
    'uri' => $uri,
    'alt' => $image->getAttribute('alt'),
  );
}

/**
 * Get a slice of the table used in the form.
 *
 * @return array
 *   Images from the table as requested by the filters and sorting.
 */
function _stanford_alt_check_get_images() {
  $header = _stanford_alt_check_table_headers();
  $rows = array();

  $row_query = db_select('stanford_alt_check', 's')
    ->extend('TableSort')
    ->orderByHeader($header)
    ->fields('s');
  $total_query = db_select('stanford_alt_check', 's')
    ->extend('TableSort')
    ->orderByHeader($header)
    ->fields('s');

  _stanford_alt_check_set_filters($row_query);
  _stanford_alt_check_set_filters($total_query);

  $total_rows = $total_query->execute()->rowCount();
  $page = pager_default_initialize($total_rows, STANFORD_ALT_CHECK_PER_PAGE);

  $results = $row_query->range(STANFORD_ALT_CHECK_PER_PAGE * $page, STANFORD_ALT_CHECK_PER_PAGE)
    ->execute();

  while ($row = $results->fetchAssoc()) {
    $row['image_meta'] = unserialize($row['image_meta']);
    $rows[] = $row;
  }

  return array($rows, $total_rows);
}

/**
 * Apply any applicable filters as defined in $_GET.
 *
 * @param TableSort $query
 *   The query to apply the conditions.
 */
function _stanford_alt_check_set_filters(TableSort &$query) {
  $get = drupal_get_query_parameters();
  foreach ($get as $key => $value) {
    if (db_field_exists('stanford_alt_check', $key) && $value != -1) {
      $value = check_plain($value);
      if ($key == 'alt_text') {
        if ($value == 'filled') {
          $query->condition('alt_text', '', '!=');
        }
        elseif ($value == 'empty') {
          $query->condition('alt_text', '', '=');
        }
      }
      else {
        $query->condition($key, $value);
      }
    }
  }
}

/**
 * Load the entity to be rescanned by stanford_alt_check_entity_update().
 *
 * @param int $entity_id
 *   Entity id to rescan.
 * @param string $type
 *   The type of the entity.
 */
function _stanford_alt_check_rescan_entity($entity_id, $type) {
  $entity = entity_load_single($type, $entity_id);
  stanford_alt_check_entity_update($entity, $type);
}

/**
 * Cron Queue work function.
 *
 * @param array $data
 *   Array of the entity id and type.
 */
function _stanford_alt_check_rescan_entity_queue(array $data) {
  list($entity_id, $type) = $data;
  if ($entity = entity_load_single($type, $entity_id)) {
    stanford_alt_check_entity_insert($entity, $type);
  }
}

/**
 * Get the table header array.
 *
 * @return array
 *   Table headers.
 */
function _stanford_alt_check_table_headers() {
  return array(
    array('data' => t('Image')),
    array('data' => t('Title'), 'field' => 's.host_title', 'sort' => 'ASC'),
    array('data' => t('Entity Type'), 'field' => 's.host_type'),
    array('data' => t('Entity Bundle'), 'field' => 's.host_bundle'),
    array('data' => t('Published'), 'field' => 's.host_published'),
    array('data' => t('Alt Attribute'), 'field' => 's.alt_text'),
    array('data' => t('Last Changed'), 'field' => 's.host_changed'),

  );
}
