<?php

/**
 * @file
 * Code for the Stanford News Item feature.
 */

include_once 'stanford_news_importers.features.inc';

/**
 * Implements hook_help().
 */
function stanford_news_importers_help($path, $arg) {
  if ($path == 'admin/structure/feeds') {
    $types = array();

    /** @var FeedsImporter $importer */
    foreach (feeds_importer_load_all() as $importer) {
      $config = $importer->getConfig();
      if ($config['content_type'] && isset($types[$config['content_type']])) {
        return '<p>' . t('If you would like to allow multiple feed importers, please enable <em>Stanford Feeds Helper Multiple</em> module.') . '</p>';
      }
      $types[$config['content_type']] = $importer;
    }
  }
}
