<?php
/**
 * @file
 * stanford_video.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function stanford_video_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-stanford_video-body'.
  $field_instances['node-stanford_video-body'] = array(
    'bundle' => 'stanford_video',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter a description of the video.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'custom_link_to_entity' => '',
          'custom_prefix' => '',
          'custom_reverse' => '',
          'custom_strip_preserve' => '',
          'custom_strip_tags' => '',
          'custom_strtolower' => '',
          'custom_strtoupper' => '',
          'custom_suffix' => '',
          'custom_trim' => '',
          'custom_ucfirst' => '',
          'custom_ucwords' => '',
        ),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'custom_link_to_entity' => '',
          'custom_prefix' => '',
          'custom_reverse' => '',
          'custom_strip_preserve' => '',
          'custom_strip_tags' => '',
          'custom_strtolower' => '',
          'custom_strtoupper' => '',
          'custom_suffix' => '',
          'custom_trim' => '',
          'custom_ucfirst' => '',
          'custom_ucwords' => '',
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Description',
    'required' => 0,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 10,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'node-stanford_video-field_stanford_video_account'.
  $field_instances['node-stanford_video-field_stanford_video_account'] = array(
    'bundle' => 'stanford_video',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the name of your account with the Stanford Video streaming service.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_account',
    'label' => 'Account Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'node-stanford_video-field_stanford_video_caption'.
  $field_instances['node-stanford_video-field_stanford_video_caption'] = array(
    'bundle' => 'stanford_video',
    'deleted' => 0,
    'description' => 'Upload a timestamped caption file (.srt, .dfxp, or similar). The captions will only appear for "Stanford Web Video" files (streaming or uploaded).',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_caption',
    'label' => 'Caption File',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'file_directory' => 'captions',
      'file_extensions' => 'txt srt dfxp xml',
      'max_filesize' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'file',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => FALSE,
        'insert_class' => '',
        'insert_default' => array(
          0 => 'auto',
        ),
        'insert_styles' => array(
          0 => 'auto',
        ),
        'insert_width' => '',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'file_generic',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-stanford_video-field_stanford_video_external'.
  $field_instances['node-stanford_video-field_stanford_video_external'] = array(
    'bundle' => 'stanford_video',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the embed code from an external video provider (e.g., YouTube, Vimeo) here.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'custom_link_to_entity' => '',
          'custom_prefix' => '',
          'custom_reverse' => '',
          'custom_strip_preserve' => '',
          'custom_strip_tags' => '',
          'custom_strtolower' => '',
          'custom_strtoupper' => '',
          'custom_suffix' => '',
          'custom_trim' => '',
          'custom_ucfirst' => '',
          'custom_ucwords' => '',
        ),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_external',
    'label' => 'External Video Embed',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 0,
          'full_html' => 'full_html',
          'plain_text' => 0,
        ),
        'allowed_formats_toggle' => 1,
        'default_order_toggle' => 1,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -49,
            ),
            'full_html' => array(
              'weight' => -50,
            ),
            'plain_text' => array(
              'weight' => -48,
            ),
          ),
        ),
      ),
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-stanford_video-field_stanford_video_file'.
  $field_instances['node-stanford_video-field_stanford_video_file'] = array(
    'bundle' => 'stanford_video',
    'deleted' => 0,
    'description' => 'Upload a video file.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'stanford_video',
        'settings' => array(
          'custom_link_to_entity' => '',
          'custom_prefix' => '',
          'custom_reverse' => '',
          'custom_strip_preserve' => '',
          'custom_strip_tags' => '',
          'custom_strtolower' => '',
          'custom_strtoupper' => '',
          'custom_suffix' => '',
          'custom_trim' => '',
          'custom_ucfirst' => '',
          'custom_ucwords' => '',
          'jwplayer_preset' => 'stanford_video',
        ),
        'type' => 'stanford_video',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_file',
    'label' => 'Video File',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'file_directory' => 'videos',
      'file_extensions' => 'mp3 mp4 m4v flv webm',
      'max_filesize' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'file',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => FALSE,
        'insert_class' => '',
        'insert_default' => array(
          0 => 'auto',
        ),
        'insert_styles' => array(
          0 => 'auto',
        ),
        'insert_width' => '',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'file_generic',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'node-stanford_video-field_stanford_video_filename'.
  $field_instances['node-stanford_video-field_stanford_video_filename'] = array(
    'bundle' => 'stanford_video',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the name of the file on the streaming server, e.g., "video.mp4" or "video.flv". If the video file is in a subdirectory, include that as well, e.g., "movies/video.flv"',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_filename',
    'label' => 'File Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-stanford_video-field_stanford_video_link'.
  $field_instances['node-stanford_video-field_stanford_video_link'] = array(
    'bundle' => 'stanford_video',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'stanford_video',
        'settings' => array(
          'custom_link_to_entity' => '',
          'custom_prefix' => '',
          'custom_reverse' => '',
          'custom_strip_preserve' => '',
          'custom_strip_tags' => '',
          'custom_strtolower' => '',
          'custom_strtoupper' => '',
          'custom_suffix' => '',
          'custom_trim' => '',
          'custom_ucfirst' => '',
          'custom_ucwords' => '',
          'jwplayer_preset' => 'stanford_video',
        ),
        'type' => 'stanford_video',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_link',
    'label' => 'Video Link',
    'required' => 0,
    'settings' => array(
      'absolute_url' => 1,
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'default',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'title' => 'none',
      'title_label_use_field_label' => FALSE,
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 0,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-stanford_video-field_stanford_video_poster'.
  $field_instances['node-stanford_video-field_stanford_video_poster'] = array(
    'bundle' => 'stanford_video',
    'deleted' => 0,
    'description' => 'Upload an image here to serve as a "keyframe" or "poster" image. This image will display when the video is stopped, before it starts playing. This will only appear for "Stanford Web Video" files (streaming or uploaded).',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_poster',
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => 'posters',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '1920x1080',
      'min_resolution' => '320x240',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => FALSE,
        'insert_class' => '',
        'insert_default' => array(
          0 => 'auto',
        ),
        'insert_styles' => array(
          0 => 'auto',
        ),
        'insert_width' => '',
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-stanford_video-field_stanford_video_server'.
  $field_instances['node-stanford_video-field_stanford_video_server'] = array(
    'bundle' => 'stanford_video',
    'default_value' => array(
      0 => array(
        'value' => 'rtmp://sv-stream.stanford.edu/',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter the URL of the streaming server. If you don\'t know what this is, you can leave it set to the default.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_stanford_video_server',
    'label' => 'Streaming Server',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Account Name');
  t('Caption File');
  t('Description');
  t('Enter a description of the video.');
  t('Enter the URL of the streaming server. If you don\'t know what this is, you can leave it set to the default.');
  t('Enter the embed code from an external video provider (e.g., YouTube, Vimeo) here.');
  t('Enter the name of the file on the streaming server, e.g., "video.mp4" or "video.flv". If the video file is in a subdirectory, include that as well, e.g., "movies/video.flv"');
  t('Enter the name of your account with the Stanford Video streaming service.');
  t('External Video Embed');
  t('File Name');
  t('Image');
  t('Streaming Server');
  t('Upload a timestamped caption file (.srt, .dfxp, or similar). The captions will only appear for "Stanford Web Video" files (streaming or uploaded).');
  t('Upload a video file.');
  t('Upload an image here to serve as a "keyframe" or "poster" image. This image will display when the video is stopped, before it starts playing. This will only appear for "Stanford Web Video" files (streaming or uploaded).');
  t('Video File');
  t('Video Link');

  return $field_instances;
}
